name: 'Asciidoctor Convert Action'
description: 'Converts .adoc files to ePUB and/or PDF files.'
author: 'Jeremy Karlsson'
branding:
  icon: book
  color: purple
inputs:
  inputBooks:
    description: 'Path the a folder that has folders with index.adoc files'
    required: false
  inputBook:
    description: 'Direct path to a single adoc file'
    required: false
  outputName:
    description: 'Name of generated files when using inputBook'
    required: false
  outputDir:
    description: 'Directory were the built files will be saved to'
    required: true
  generateEpub:
    description: 'If you want to generate ePUB or not'
    required: false
    default: 'true'
  generatePdf:
    description: 'If you want to generate PDF or not'
    required: false
    default: 'true'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.inputDir }}
    - ${{ inputs.inputBook }}
    - ${{ inputs.outputName }}
    - ${{ inputs.outputDir }}
    - ${{ inputs.generateEpub }}
    - ${{ inputs.generatePdf }}
