name: 'Asciidoctor Convert Action'
description: 'Converts .adoc files to ePUB and/or PDF files.'
author: 'Jeremy Karlsson'
branding:
  icon: book
  color: pink
inputs:
  inputPath:
    description: 'Path the adoc files are located in'
    required: true
  outputPath:
    description: 'Path were the built files will be saved to'
    required: true
  generateEpub:
    description: 'If you want to generate ePUB or not'
    required: false
    default: 'true'
  generatePdf:
    description: 'If you want to generate PDF or not'
    required: false
    default: 'true'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.inputPath }}
    - ${{ inputs.outputPath }}
    - ${{ inputs.generateEpub }}
    - ${{ inputs.generatePdf }}
