on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - name: Build books
        id: build
        uses: enjikaka/asciidoctor-convert-action@v0.1
        with:
          inputPath: test_input_path
          outputPath: build
