on: [push]

jobs:
  press_books:
    runs-on: ubuntu-latest
    name: Press books
    steps:
      - uses: actions/checkout@v4
      - uses: enjikaka/asciidoctor-convert-action@v0.16
        name: Build books
        with:
          inputDir: test_input_path
          outputDir: build
      - uses: actions/upload-artifact@v4
        with:
          name: books
          path: build
