on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - uses: enjikaka/asciidoctor-convert-action@v0.2
        name: Build books
        with:
          inputPath: test_input_path
          outputPath: build
      - uses: actions/upload-artifact@v4
        with:
          name: books
          path: build
